package com.mycompany.GUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import com.mycompany.staffmodule.Doctor;
import com.mycompany.staffmodule.User;
import java.awt.*;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Calendar;
import java.util.HashSet;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.SpinnerDateModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import java.util.TreeSet;
import javax.swing.SwingUtilities;

/**
 *
 * @author amar2
 */
public class Do extends javax.swing.JFrame {

   private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(Do.class.getName());

    // ---- Card names ----
    private static final String CARD_PROFILE    = "card_profile";
    private static final String CARD_APPT_MGMT  = "card_appt_mgmt";
    private static final String CARD_REPORTS    = "card_reports";

    // ---- Layout host ----
    private final CardLayout cardLayout = new CardLayout();
    private final JPanel cardHost = new JPanel(cardLayout);

    // ---- Top / sidebar ----
    private JLabel lblTitle;
    private JButton btnLogout;
    private JButton btnNavProfile, btnNavApptMgmt, btnNavReports;

    // ---- Profile fields ----
    private JTextField tfId, tfName, tfEmail, tfPhone, tfSalary, tfSpecialisation;
    private JPasswordField pfPassword;
    private JComboBox<String> cbGender;
    private JSpinner spAge;
    private JButton btnProfileSave, btnProfileCancel;

    // ---- Appointment management ----
    private JComboBox<String> cbApptStatus;
    private JTextArea taDoctorFeedback;
    private JTextField tfExtraCharges;
    private JSpinner spFinishedTime;
    private JButton btnApptSave, btnApptCancel;
    private JTable tblAppts;
    private DefaultTableModel apptModel;

    // ---- Reports ----
    private JTable tblReports;
    private JComboBox<String> cbCustomerFilter, cbDate, cbAppointments, cbSortCharges;

    // ---- Backend service / state ----
    private final Doctor service = new Doctor();
    private Doctor currentDoctor;
    private static String CURRENT_DOCTOR_ID;

    /**
     * Creates new form Doctor
     */


public Do(Doctor doctor) {
    this.currentDoctor = doctor;
    CURRENT_DOCTOR_ID = doctor.getId();
    initComponents();
    buildUI();

    // Fill profile with passed doctor (instead of typing ID)
    if (currentDoctor != null) {
        fillFormFromDoctor();
    }

    // Once UI exists, setup filters & events
    SwingUtilities.invokeLater(() -> {
        loadCustomersIntoFilter();
        loadDateFilter();
        loadAppointmentsFilter();
        loadChargesFilter();
        wireEvents();
        hookAppointmentSelection();
        wireApptSaveAction();
    });
}

// Keep a default constructor (for dummy/testing only)
public Do() {
    this(new Doctor());
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void fillFormFromDoctor() {
    if (currentDoctor == null) return;
    tfId.setText(currentDoctor.getId()); tfId.setEditable(false);
    tfName.setText(currentDoctor.getName());
    pfPassword.setText(currentDoctor.getPassword());
    tfEmail.setText(currentDoctor.getEmail());
    cbGender.setSelectedItem(currentDoctor.getGender());
    tfPhone.setText(currentDoctor.getPhoneNum());
    spAge.setValue(currentDoctor.getAge());
    tfSalary.setText(String.valueOf(currentDoctor.getSalary())); tfSalary.setEditable(false);
    tfSpecialisation.setText(currentDoctor.getPosition()); tfSpecialisation.setEditable(false);
}
    

  private void buildUI() {
        JPanel root = new JPanel(new BorderLayout());
        setContentPane(root);

        // ---- Top bar ----
        JPanel topBar = new JPanel(new BorderLayout());
        topBar.setBorder(new EmptyBorder(10, 16, 10, 16));
        topBar.setBackground(new Color(65, 105, 225));
        lblTitle = new JLabel("Doctor Portal");
        lblTitle.setForeground(Color.WHITE);
        lblTitle.setFont(lblTitle.getFont().deriveFont(Font.BOLD, 18f));
        btnLogout = new JButton("Logout");
        styleButton(btnLogout, new Color(220, 20, 60));
        topBar.add(lblTitle, BorderLayout.WEST);
        topBar.add(btnLogout, BorderLayout.EAST);

        // ---- Sidebar ----
        JPanel sidebar = new JPanel(new GridLayout(0, 1, 8, 8));
        sidebar.setPreferredSize(new Dimension(210, 700));
        sidebar.setBorder(new EmptyBorder(12, 12, 12, 12));
        sidebar.setBackground(new Color(255, 228, 225));
        btnNavProfile   = new JButton("Own Profile");
        btnNavApptMgmt  = new JButton("Appointment Management");
        btnNavReports   = new JButton("Reports");
        styleButton(btnNavProfile,  new Color(100, 149, 237));
        styleButton(btnNavApptMgmt, new Color(60, 179, 113));
        styleButton(btnNavReports,  new Color(255, 140, 0));
        sidebar.add(btnNavProfile);
        sidebar.add(btnNavApptMgmt);
        sidebar.add(btnNavReports);

        // ---- Cards ----
        cardHost.add(buildProfileCard(),        CARD_PROFILE);
        cardHost.add(buildApptManagementCard(), CARD_APPT_MGMT);
        cardHost.add(buildReportsCard(),        CARD_REPORTS);

        // ---- Assemble ----
        root.add(topBar, BorderLayout.NORTH);
        root.add(sidebar, BorderLayout.WEST);
        root.add(cardHost, BorderLayout.CENTER);

        cardLayout.show(cardHost, CARD_PROFILE);
        setSize(1000, 650);
        setLocationRelativeTo(null);
    }

    // ========================= Profile =========================
    private JPanel buildProfileCard() {
        JPanel p = new JPanel(new GridBagLayout());
        p.setBackground(new Color(255, 248, 220));
        GridBagConstraints gc = new GridBagConstraints();
        gc.insets = new Insets(8, 8, 8, 8);
        gc.fill = GridBagConstraints.HORIZONTAL;
        gc.weightx = 1.0;

        int y = 0;
        gc.gridx = 0; gc.gridy = y; p.add(new JLabel("Doctor ID"), gc);
        tfId = new JTextField(); gc.gridx = 1; p.add(tfId, gc); y++;

        gc.gridx = 0; gc.gridy = y; p.add(new JLabel("Name"), gc);
        tfName = new JTextField(); gc.gridx = 1; p.add(tfName, gc); y++;

        gc.gridx = 0; gc.gridy = y; p.add(new JLabel("Password"), gc);
        pfPassword = new JPasswordField(); gc.gridx = 1; p.add(pfPassword, gc); y++;

        gc.gridx = 0; gc.gridy = y; p.add(new JLabel("Email"), gc);
        tfEmail = new JTextField(); gc.gridx = 1; p.add(tfEmail, gc); y++;

        gc.gridx = 0; gc.gridy = y; p.add(new JLabel("Gender"), gc);
        cbGender = new JComboBox<>(new String[]{"Male", "Female"}); gc.gridx = 1; p.add(cbGender, gc); y++;

        gc.gridx = 0; gc.gridy = y; p.add(new JLabel("Phone"), gc);
        tfPhone = new JTextField(); gc.gridx = 1; p.add(tfPhone, gc); y++;

        gc.gridx = 0; gc.gridy = y; p.add(new JLabel("Age"), gc);
        spAge = new JSpinner(new SpinnerNumberModel(25, 18, 65, 1)); gc.gridx = 1; p.add(spAge, gc); y++;

        gc.gridx = 0; gc.gridy = y; p.add(new JLabel("Salary"), gc);
        tfSalary = new JTextField(); gc.gridx = 1; p.add(tfSalary, gc); y++;

        gc.gridx = 0; gc.gridy = y; p.add(new JLabel("Specialisation"), gc);
        tfSpecialisation = new JTextField(); gc.gridx = 1; p.add(tfSpecialisation, gc); y++;

        btnProfileSave   = new JButton("Save");
        btnProfileCancel = new JButton("Cancel");
        JPanel actions = new JPanel();
        actions.add(btnProfileCancel);
        actions.add(btnProfileSave);
        gc.gridx = 0; gc.gridy = y; gc.gridwidth = 2; p.add(actions, gc);

        tfId.addActionListener(e -> loadDoctorById(tfId.getText().trim()));
        btnProfileSave.addActionListener(e -> {
            
            onSaveProfile();
        
        });
        btnProfileCancel.addActionListener(e -> fillFormFromDoctor());
        return p;
    }

    private void loadDoctorById(String docId) {
        if (docId == null || docId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter a Doctor ID (e.g., D006).");
            return;
        }
        Doctor found = Doctor.findById(docId);
        if (found == null) {
            JOptionPane.showMessageDialog(this, "Doctor not found: " + docId,
                    "Not found", JOptionPane.WARNING_MESSAGE);
            return;
        }
        currentDoctor = found;
        fillFormFromDoctor();
    }



private void onSaveProfile() {
    if (currentDoctor == null) {
        JOptionPane.showMessageDialog(this, "No doctor loaded.");
        return;
    }
    String email   = tfEmail.getText().trim();
    String pwd     = new String(pfPassword.getPassword());
    String name    = tfName.getText().trim();
    String gender  = String.valueOf(cbGender.getSelectedItem());
    String phone   = tfPhone.getText().trim();
    int    age     = (Integer) spAge.getValue();
    double salary;
    try { salary = Double.parseDouble(tfSalary.getText().trim()); }
    catch (Exception ex) { JOptionPane.showMessageDialog(this,"Salary must be numeric."); return; }
    String position = tfSpecialisation.getText().trim();
    
    User saveDoc = new Doctor();
    
    //validation
            if(!saveDoc.emailValidation(email)){
                JOptionPane.showMessageDialog(this, "Invalid Email !!!");
            }
            else if(!saveDoc.passwordValidation(pwd)){
                JOptionPane.showMessageDialog(this, "Invalid Password !!! Password must be 8 character, including uppercase, lowercase, special character and number");
            }
            else if(!saveDoc.phoneNumValidation(phone)){
                JOptionPane.showMessageDialog(this, "Invalid Phone Number !!!");
            }
            else if(!saveDoc.ageValidation(age)){
                JOptionPane.showMessageDialog(this, "Invalid Age !!! Age must between 18 and 65");
            }
            else{
                boolean ok = currentDoctor.updateProfile(email, pwd, name, gender, phone, age, salary, position);
                JOptionPane.showMessageDialog(this, ok ? "Profile saved." : "Save failed.");
                if (ok) fillFormFromDoctor();
            }

    
}


    // ========================= Appointment Management =========================
    private JPanel buildApptManagementCard() {
        JPanel host = new JPanel(new BorderLayout());
        host.setBorder(new EmptyBorder(16, 16, 16, 16));
        host.setBackground(new Color(248, 248, 255));

        JLabel title = new JLabel("Manage Appointment");
        title.setFont(title.getFont().deriveFont(Font.BOLD, 16f));
        host.add(title, BorderLayout.NORTH);

        JPanel content = new JPanel(new GridBagLayout());
        content.setOpaque(false);
        GridBagConstraints gc = new GridBagConstraints();
        gc.insets = new Insets(8, 8, 8, 8);
        gc.fill = GridBagConstraints.HORIZONTAL;
        gc.anchor = GridBagConstraints.FIRST_LINE_START;
        gc.weightx = 1.0;

        // ---- Details ----
        JPanel grpDetails = new JPanel(new GridBagLayout());
        grpDetails.setBorder(BorderFactory.createTitledBorder("Appointment Details"));
        grpDetails.setBackground(new Color(250, 250, 210));
        GridBagConstraints dgc = new GridBagConstraints();
        dgc.insets = new Insets(6, 8, 6, 8);
        dgc.fill = GridBagConstraints.HORIZONTAL;
        dgc.anchor = GridBagConstraints.LINE_START;
        dgc.weightx = 1.0;

        int r = 0;
        dgc.gridx = 0; dgc.gridy = r; grpDetails.add(new JLabel("Appointment Status"), dgc);
        cbApptStatus = new JComboBox<>(new String[]{"booked", "conducting", "completed", "cancel"});
        cbApptStatus.setSelectedIndex(-1);
        dgc.gridx = 1; grpDetails.add(cbApptStatus, dgc); r++;

//        dgc.gridx = 0; dgc.gridy = r; grpDetails.add(new JLabel("Finished Time"), dgc);
        spFinishedTime = createTimeSpinner(LocalTime.now());
//        dgc.gridx = 1; grpDetails.add(spFinishedTime, dgc); r++;

        dgc.gridx = 0; dgc.gridy = r; grpDetails.add(new JLabel("Extra Charges"), dgc);
        tfExtraCharges = new JTextField();
        dgc.gridx = 1; grpDetails.add(tfExtraCharges, dgc); r++;

        gc.gridx = 0; gc.gridy = 0; gc.weightx = 0.5; content.add(grpDetails, gc);

        // ---- Feedback ----
        JPanel grpFeedback = new JPanel(new BorderLayout());
        grpFeedback.setBorder(BorderFactory.createTitledBorder("Doctor Feedback"));
        grpFeedback.setBackground(new Color(250, 250, 210));
        taDoctorFeedback = new JTextArea(6, 30);
        taDoctorFeedback.setLineWrap(true);
        taDoctorFeedback.setWrapStyleWord(true);
        grpFeedback.add(new JScrollPane(taDoctorFeedback), BorderLayout.CENTER);

        gc.gridx = 1; gc.gridy = 0; gc.weightx = 0.5; content.add(grpFeedback, gc);

        // ---- Actions ----
        JPanel actions = new JPanel(new FlowLayout(FlowLayout.RIGHT, 8, 0));
        btnApptCancel = new JButton("Cancel");
        styleButton(btnApptCancel, new Color(220, 20, 60));
        btnApptSave = new JButton("Save");
        styleButton(btnApptSave, new Color(46, 139, 87));
        actions.add(btnApptCancel);
        actions.add(btnApptSave);
        btnApptCancel.addActionListener(e -> resetAppointmentFields());

        gc.gridx = 0; gc.gridy = 1; gc.gridwidth = 2; content.add(actions, gc);

        // ---- Table ----
        String[] apptCols = {
            "Appt ID","Date","Time","Feedback","Charge","Payment Status",
            "Status","Comment","Rating","Customer ID","Doctor ID","Staff ID"
        };
        apptModel = new DefaultTableModel(apptCols, 0) {
            @Override public boolean isCellEditable(int r, int c) { return false; }
        };
        tblAppts = new JTable(apptModel);
        tblAppts.setAutoCreateRowSorter(true);
        tblAppts.setRowHeight(24);

        GridBagConstraints tgc = new GridBagConstraints();
        tgc.gridx = 0; tgc.gridy = 2; tgc.gridwidth = 2;
        tgc.insets = new Insets(8, 8, 8, 8);
        tgc.fill = GridBagConstraints.BOTH;
        tgc.weightx = 1.0; tgc.weighty = 1.0;
        content.add(new JScrollPane(tblAppts), tgc);

        host.add(content, BorderLayout.CENTER);
        return host;
    }

    private void loadTodayAppointmentsIntoTable() {
        if (apptModel == null) return;
        apptModel.setRowCount(0);
        try {
            for (Object[] row : service.loadTodayUnpaidAsTableRowsForDoctor(CURRENT_DOCTOR_ID)) {
                System.out.println(CURRENT_DOCTOR_ID);
                apptModel.addRow(row);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Failed to load today's unpaid appointments:\n" + ex.getMessage(),
                    "Load Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void hookAppointmentSelection() {
        if (tblAppts == null) return;
        tblAppts.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblAppts.getSelectionModel().addListSelectionListener(e -> {
            if (e.getValueIsAdjusting()) return;
            int vRow = tblAppts.getSelectedRow();
            if (vRow < 0) return;
            int row = tblAppts.convertRowIndexToModel(vRow);

            String feedback = String.valueOf(apptModel.getValueAt(row, 3));
            String charge   = String.valueOf(apptModel.getValueAt(row, 4));
            String status   = String.valueOf(apptModel.getValueAt(row, 6));
            String comment  = String.valueOf(apptModel.getValueAt(row, 7));

            taDoctorFeedback.setText(feedback);
            tfExtraCharges.setText(charge);
            cbApptStatus.setSelectedItem(status);

            LocalTime fin = parseFinishedFromComment(comment);
            if (fin != null) setSpinnerLocalTime(spFinishedTime, fin);
        });
    }

    private void wireApptSaveAction() {
        btnApptSave.addActionListener(ae -> {
            int vRow = tblAppts.getSelectedRow();
            if (vRow < 0) {
                JOptionPane.showMessageDialog(this, "Select an appointment first.",
                        "No selection", JOptionPane.WARNING_MESSAGE);
                return;
            }
            int row = tblAppts.convertRowIndexToModel(vRow);
            String appId = String.valueOf(apptModel.getValueAt(row, 0));

            try {
                String chargeText = tfExtraCharges.getText().trim();
                Double.parseDouble(chargeText); // validate numeric

                boolean ok = service.updateAppointmentFields(
                        appId,
                        getSpinnerLocalTime(spFinishedTime),
                        taDoctorFeedback.getText().trim(),
                        (String) cbApptStatus.getSelectedItem(),
                        chargeText
                );

                if (ok) {
                    loadTodayAppointmentsIntoTable();
                    reselectByAppId(appId);
                    JOptionPane.showMessageDialog(this, "Appointment updated.",
                            "Saved", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Appointment not found: " + appId,
                            "Warning", JOptionPane.WARNING_MESSAGE);
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this,
                        "Extra Charges must be numeric (e.g., 500 or 500.50).",
                        "Validation Error", JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Failed to save:\n" + ex.getMessage(),
                        "Save Error", JOptionPane.ERROR_MESSAGE);
            }
        });
    }

    private void resetAppointmentFields() {
        int vRow = (tblAppts == null) ? -1 : tblAppts.getSelectedRow();
        if (vRow < 0) return;
        int row = tblAppts.convertRowIndexToModel(vRow);
        taDoctorFeedback.setText(String.valueOf(apptModel.getValueAt(row, 3)));
        tfExtraCharges.setText(String.valueOf(apptModel.getValueAt(row, 4)));
        cbApptStatus.setSelectedItem(String.valueOf(apptModel.getValueAt(row, 6)));
        LocalTime fin = parseFinishedFromComment(String.valueOf(apptModel.getValueAt(row, 7)));
        spFinishedTime.setValue(Calendar.getInstance().getTime());
        if (fin != null) setSpinnerLocalTime(spFinishedTime, fin);
    }

    // ========================= Reports =========================
    private JPanel buildReportsCard() {
        JPanel p = new JPanel(new BorderLayout());
        p.setBorder(new EmptyBorder(16, 16, 16, 16));
        p.setBackground(new Color(245, 245, 245));

        JLabel title = new JLabel("Reports");
        title.setFont(title.getFont().deriveFont(Font.BOLD, 16f));
        p.add(title, BorderLayout.NORTH);

        JPanel filters = new JPanel(new FlowLayout(FlowLayout.LEFT));
        cbCustomerFilter = new JComboBox<>(new String[]{});
        filters.add(new JLabel("Customer:"));
        filters.add(cbCustomerFilter);

        cbDate = new JComboBox<>(new String[]{});
        filters.add(new JLabel("Date:"));
        filters.add(cbDate);

        cbAppointments = new JComboBox<>(new String[]{});
        filters.add(new JLabel("Appointments:"));
        filters.add(cbAppointments);

        cbSortCharges = new JComboBox<>(new String[]{});
        filters.add(new JLabel("Sort Charges:"));
        filters.add(cbSortCharges);

        p.add(filters, BorderLayout.NORTH);

        String[] cols = {"Appt ID","Customer","Doctor","Date","Status","Charges","Customer Feedback"};
        tblReports = new JTable(new DefaultTableModel(cols, 0));
        tblReports.setRowHeight(24);
        p.add(new JScrollPane(tblReports), BorderLayout.CENTER);

        // on change -> reload
        cbCustomerFilter.addActionListener(e -> reloadReportsTable());
        cbDate.addActionListener(e -> reloadReportsTable());
        cbAppointments.addActionListener(e -> reloadReportsTable());
        cbSortCharges.addActionListener(e -> reloadReportsTable());

        return p;
    }

    private void reloadReportsTable() {
        DefaultTableModel model = (DefaultTableModel) tblReports.getModel();
        model.setRowCount(0);

        try {
            String dateFilter = (String) cbDate.getSelectedItem();            // All / Daily / Monthly / Yearly
            String apptFilter = (String) cbAppointments.getSelectedItem();    // All / Previous / Upcoming / Today
            String sortChoice = (String) cbSortCharges.getSelectedItem();     // All / High → Low / Low → High
            String customer   = (String) cbCustomerFilter.getSelectedItem();  // All or concrete ID

            List<Object[]> rows = service.loadAllAsReportRows();

            // Customer filter (column 1)
            if (customer != null && !"All".equalsIgnoreCase(customer)) {
                rows = rows.stream().filter(r -> Objects.equals(r[1], customer)).toList();
            }

            // Date filter (column 3 = yyyy-MM-dd)
            LocalDate today = LocalDate.now();
            if ("Daily".equalsIgnoreCase(dateFilter)) {
                rows = rows.stream().filter(r ->
                        LocalDate.parse(String.valueOf(r[3])).equals(today)
                ).toList();
            } else if ("Monthly".equalsIgnoreCase(dateFilter)) {
                rows = rows.stream().filter(r -> {
                    LocalDate d = LocalDate.parse(String.valueOf(r[3]));
                    return d.getYear() == today.getYear() && d.getMonth() == today.getMonth();
                }).toList();
            } else if ("Yearly".equalsIgnoreCase(dateFilter)) {
                rows = rows.stream().filter(r ->
                        LocalDate.parse(String.valueOf(r[3])).getYear() == today.getYear()
                ).toList();
            }

            // Appointment filter by date relative to today
            if ("Previous Appointments".equalsIgnoreCase(apptFilter)) {
                rows = rows.stream().filter(r ->
                        LocalDate.parse(String.valueOf(r[3])).isBefore(today)
                ).toList();
            } else if ("Upcoming Appointments".equalsIgnoreCase(apptFilter)) {
                rows = rows.stream().filter(r ->
                        LocalDate.parse(String.valueOf(r[3])).isAfter(today)
                ).toList();
            } else if ("Today Appointments".equalsIgnoreCase(apptFilter)) {
                rows = rows.stream().filter(r ->
                        LocalDate.parse(String.valueOf(r[3])).isEqual(today)
                ).toList();
            }

            // Sort by Charges (column 5)
            if ("High → Low".equals(sortChoice)) {
                rows = rows.stream()
                        .sorted((a,b) -> Double.compare(
                                parseDoubleSafe(b[5]), parseDoubleSafe(a[5])))
                        .toList();
            } else if ("Low → High".equals(sortChoice)) {
                rows = rows.stream()
                        .sorted((a,b) -> Double.compare(
                                parseDoubleSafe(a[5]), parseDoubleSafe(b[5])))
                        .toList();
            }

            for (Object[] row : rows) model.addRow(row);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Failed to load reports:\n" + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private static double parseDoubleSafe(Object o) {
        try { return Double.parseDouble(String.valueOf(o)); }
        catch (Exception e) { return 0.0; }
    }

    private void loadCustomersIntoFilter() {
        try {
            List<Object[]> rows = service.loadAllAsReportRows();
            Set<String> customers = new TreeSet<>();
            for (Object[] r : rows) customers.add(String.valueOf(r[1]));
            cbCustomerFilter.removeAllItems();
            cbCustomerFilter.addItem("All");
            for (String c : customers) cbCustomerFilter.addItem(c);
        } catch (Exception e) {
            cbCustomerFilter.removeAllItems();
            cbCustomerFilter.addItem("All");
        }
    }

    private void loadDateFilter() {
        cbDate.removeAllItems();
        cbDate.addItem("All");
        cbDate.addItem("Daily");
        cbDate.addItem("Monthly");
        cbDate.addItem("Yearly");
        cbDate.setSelectedItem("All");
    }

    private void loadAppointmentsFilter() {
        cbAppointments.removeAllItems();
        cbAppointments.addItem("All");
        cbAppointments.addItem("Previous Appointments");
        cbAppointments.addItem("Upcoming Appointments");
        cbAppointments.addItem("Today Appointments");
        cbAppointments.setSelectedItem("All");
    }

    private void loadChargesFilter() {
        cbSortCharges.removeAllItems();
        cbSortCharges.addItem("All");
        cbSortCharges.addItem("High → Low");
        cbSortCharges.addItem("Low → High");
        cbSortCharges.setSelectedItem("All");
    }

    // ========================= Wiring / helpers =========================
    private void wireEvents() {
        btnNavProfile.addActionListener(e -> cardLayout.show(cardHost, CARD_PROFILE));
        btnNavApptMgmt.addActionListener(e -> {
            cardLayout.show(cardHost, CARD_APPT_MGMT);
            loadTodayAppointmentsIntoTable();
        });
        btnLogout.addActionListener(e -> {
    // Dispose (close) the current Doctor UI window
    this.dispose();

    // Open the login screen again
    SwingUtilities.invokeLater(() -> new Login().setVisible(true));
});

        
        btnNavReports.addActionListener(e -> {
            cardLayout.show(cardHost, CARD_REPORTS);
            reloadReportsTable();
        });
//        btnLogout.addActionListener(e -> System.exit(0));
btnLogout.addActionListener(e -> {
    // Dispose (close) the current Doctor UI window
    JOptionPane.showMessageDialog(this, "Logout clicked");
    dispose();

    // Open the login screen again
//    SwingUtilities.invokeLater(() -> new Login().setVisible(true));
});
    }

    private JSpinner createTimeSpinner(LocalTime time) {
        Calendar cal = Calendar.getInstance();
        cal.set(Calendar.HOUR_OF_DAY, time.getHour());
        cal.set(Calendar.MINUTE, time.getMinute());
        cal.set(Calendar.SECOND, 0);
        cal.set(Calendar.MILLISECOND, 0);
        SpinnerDateModel model = new SpinnerDateModel(cal.getTime(), null, null, Calendar.MINUTE);
        JSpinner spinner = new JSpinner(model);
        JSpinner.DateEditor editor = new JSpinner.DateEditor(spinner, "HH:mm");
        spinner.setEditor(editor);
        return spinner;
    }

    private LocalTime parseFinishedFromComment(String comment) {
        if (comment == null || comment.isEmpty()) return null;
        String[] tokens = comment.split("[;\\s]+");
        for (String t : tokens) {
            if (t.startsWith("FIN=")) {
                String hhmm = t.substring(4).trim();
                try { return LocalTime.parse(hhmm); } catch (Exception ignored) {}
            }
        }
        return null;
    }

    private LocalTime getSpinnerLocalTime(JSpinner spinner) {
        Object v = spinner.getValue();
        if (v instanceof java.util.Date d) {
            return d.toInstant().atZone(java.time.ZoneId.systemDefault())
                    .toLocalTime().withSecond(0).withNano(0);
        }
        try {
            return LocalTime.parse(((JSpinner.DefaultEditor) spinner.getEditor())
                    .getTextField().getText());
        } catch (Exception ignored) { return null; }
    }

    private void setSpinnerLocalTime(JSpinner spinner, LocalTime t) {
        Calendar cal = Calendar.getInstance();
        cal.set(Calendar.HOUR_OF_DAY, t.getHour());
        cal.set(Calendar.MINUTE, t.getMinute());
        cal.set(Calendar.SECOND, 0);
        cal.set(Calendar.MILLISECOND, 0);
        spinner.setValue(cal.getTime());
    }

    private void reselectByAppId(String appId) {
        if (tblAppts == null) return;
        for (int i = 0; i < apptModel.getRowCount(); i++) {
            if (appId.equals(String.valueOf(apptModel.getValueAt(i, 0)))) {
                int vIndex = tblAppts.convertRowIndexToView(i);
                tblAppts.getSelectionModel().setSelectionInterval(vIndex, vIndex);
                tblAppts.scrollRectToVisible(tblAppts.getCellRect(vIndex, 0, true));
                break;
            }
        }
    }

    private void styleButton(JButton b, Color bg) {
        b.setBackground(bg);
        b.setForeground(Color.WHITE);
        b.setFocusPainted(false);
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new Do().setVisible(false));
    }

        //</editor-fold>

        /* Create and display the form */
        

    

}
