/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.GUI;



import com.mycompany.staffmodule.Customer;
import com.mycompany.staffmodule.Staff;
import com.mycompany.staffmodule.Doctor;
import com.mycompany.staffmodule.Manager;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
/**
 *
 * @author amar2
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());
      

    // UI (not in generated section)
    private JTextField tfEmail;
    private JPasswordField pfPassword;
    private JButton btnLogin;
    private JCheckBox loginShowPassword;

    // Config
    private static final String USER_FILE = "User.txt";
    private static final String Customer_FILE = "Customer.txt";
    private static final boolean REQUIRE_PASSWORD = true;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
         buildUI();          // (our custom UI)
        wireEvents();
        setTitle("Login");
        setSize(420, 240);
        setLocationRelativeTo(null);
    }
    
   

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
                         

    private void buildUI() {
        JPanel root = new JPanel(new BorderLayout());
        root.setBorder(new EmptyBorder(16, 16, 16, 16));
        setContentPane(root);

        JLabel title = new JLabel("Login");
        title.setFont(title.getFont().deriveFont(Font.BOLD, 18f));
        root.add(title, BorderLayout.NORTH);

        JPanel form = new JPanel(new GridBagLayout());
        GridBagConstraints gc = new GridBagConstraints();
        gc.insets = new Insets(8, 8, 8, 8);
        gc.fill = GridBagConstraints.HORIZONTAL;
        gc.weightx = 1.0;

        tfEmail = new JTextField();
        pfPassword = new JPasswordField();
        btnLogin = new JButton("Login");
        loginShowPassword = new JCheckBox("Show Password");

        int y = 0;
        gc.gridx = 0; gc.gridy = y; form.add(new JLabel("Email"), gc);
        gc.gridx = 1; form.add(tfEmail, gc); y++;

        gc.gridx = 0; gc.gridy = y; form.add(new JLabel("Password"), gc);
        gc.gridx = 1; form.add(pfPassword, gc); y++;
        
        gc.gridx = 1; gc.gridy = y; form.add(loginShowPassword, gc); y++;

        JPanel actions = new JPanel(new FlowLayout(FlowLayout.RIGHT, 8, 0));
        actions.add(btnLogin);

        gc.gridx = 0; gc.gridy = y; gc.gridwidth = 2;
        form.add(actions, gc);

        root.add(form, BorderLayout.CENTER);
    }

    private void wireEvents() {
        btnLogin.addActionListener(e -> doLogin());
        pfPassword.addActionListener(e -> doLogin()); // Enter key in password field
        loginShowPassword.addActionListener(e -> {
            if (loginShowPassword.isSelected()) {
                // Show password
                pfPassword.setEchoChar((char) 0);
            } else {
                // Hide password
                pfPassword.setEchoChar('*');
            }
        });
    }

   private void doLogin() {
    String email = tfEmail.getText().trim();
    String password = new String(pfPassword.getPassword());

    if (email.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter your email.");
        return;
    }

    // 1) First check in User.txt
    UserRow row = findUserByEmail(email, USER_FILE, true);
    if (row != null) {
        if (REQUIRE_PASSWORD && !row.password.equals(password)) {
            JOptionPane.showMessageDialog(this, "Invalid password.");
            return;
        }

        switch (row.role.toLowerCase()) {
            case "manager" -> {
                Manager mg = new Manager(
                        row.email, row.password, row.name, row.gender,
                        row.phone, row.age, row.id, row.salary, row.position, "Manager"
                );
                ManagerDesign frame = new ManagerDesign(mg);
                frame.setVisible(true);
                dispose();
            }
            case "staff" -> {
                Staff st = new Staff(
                        row.email, row.password, row.name, row.gender,
                        row.phone, row.age, row.id, row.salary, row.position, "Staff"
                );
                StaffUI frame = new StaffUI(st);
                frame.setVisible(true);
                dispose();
            }
           case "doctor" -> {
    Doctor doc = new Doctor(
        row.email,
        row.password,
        row.name,
        row.gender,
        row.phone,
        row.age,
        row.id,
        row.salary,
        row.position,
        "Doctor"
    );
    Do frame = new Do(doc); // ✅ pass doctor object
    frame.setVisible(true);
    dispose();
}

            default -> JOptionPane.showMessageDialog(this, "Unknown role: " + row.role);
        }
        return; // stop here, user found
    }

    // 2) If not in User.txt, check Customer.txt
    UserRow custRow = findUserByEmail(email, Customer_FILE, false);
    if (custRow != null) {
        if (REQUIRE_PASSWORD && !custRow.password.equals(password)) {
            JOptionPane.showMessageDialog(this, "Invalid password.");
            return;
        }

        Customer cust = new Customer(
                custRow.email, custRow.password, custRow.name, custRow.gender,
                custRow.phone, custRow.age, custRow.id
        );
        Customerrr frame = new Customerrr(cust);
        frame.setVisible(true);
        dispose();
        return;
    }

    // 3) Not found in either file
    JOptionPane.showMessageDialog(this, "Email not found in system.");
}


    /** Minimal record of a row from User.txt */
    private static class UserRow {
        String email, password, name, gender, phone, id, position, role;
        int age;
        double salary;
    }

//    /** Find User.txt row by email (case-insensitive) and parse the fields */
 private UserRow findUserByEmail(String email, String filePath, boolean hasRole) {
    try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {
        String line;
        while ((line = br.readLine()) != null) {
            // email|password|name|gender|phone|age|id|salary|position|role   (User.txt)
            // email|password|name|gender|phone|age|id                       (Customer.txt)
            String[] p = line.split("\\|", -1);

            if (p.length < 7) continue; // must have at least 7 columns
            if (p[0].equalsIgnoreCase(email)) {
                UserRow r = new UserRow();
                r.email = p[0];
                r.password = p[1];
                r.name = p[2];
                r.gender = p[3];
                r.phone = p[4];
                try { r.age = Integer.parseInt(p[5]); } catch (NumberFormatException e) { r.age = 0; }
                r.id = p[6];
                if (hasRole) {
                    try { r.salary = Double.parseDouble(p[7]); } catch (NumberFormatException e) { r.salary = 0.0; }
                    r.position = p[8];
                    r.role = p[9];
                } else {
                    r.salary = 0.0;
                    r.position = "Customer";
                    r.role = "Customer";
                }
                return r;
            }
        }
    } catch (IOException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Failed to read " + filePath + ": " + e.getMessage());
    }
    return null;
}

    
    /**
     * @param args the command line arguments
     */
   public static void login() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
